# -*- coding: utf-8 -*-
"""day10_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3mMwG7W0xtNtsjysKyD0aN-_N3FbZbq
"""

!pip install groq pyspark reportlab pandas scikit-learn -q

import pandas as pd
import numpy as np
from groq import Groq

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from pyspark.sql import SparkSession

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

GROQ_API_KEY = "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"

client = Groq(
    api_key=GROQ_API_KEY
)

print("Groq Connected")

user_prompt = """
Analyze Employee Attrition Dataset.

Tasks:

1. Clean data
2. Perform feature engineering
3. Encode categorical columns
4. Scale numerical columns
5. Generate analytics
6. Produce final report
"""

print(user_prompt)

file_path = "employee.csv"

df = pd.read_csv(
    file_path
)

print(df.shape)

df.head()

prompt = f"""
Analyze this dataset.

Columns:

{list(df.columns)}

Provide:

1. Dataset Summary
2. Data Cleaning Suggestions
3. Feature Engineering Suggestions
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role":"user",
            "content":prompt
        }
    ]
)

analysis = response.choices[0].message.content

print(analysis)

df = df.drop_duplicates()

for col in df.columns:

    if df[col].dtype == "object":

        df[col] = df[col].fillna(
            df[col].mode()[0]
        )

    else:

        df[col] = df[col].fillna(
            df[col].median()
        )

print("Cleaning Completed")

df["YearsAtCompanyRatio"] = (
    df["YearsAtCompany"]
    /
    (df["TotalWorkingYears"] + 1)
)

df["IncomePerYear"] = (
    df["MonthlyIncome"] * 12
)

df["OverTimeFlag"] = (
    df["OverTime"] == "Yes"
).astype(int)

print("Feature Engineering Completed")

encoder = LabelEncoder()

for col in df.select_dtypes(
    include="object"
).columns:

    df[col] = encoder.fit_transform(
        df[col]
    )

print("Encoding Completed")

scaler = StandardScaler()

numeric_cols = df.columns

df[numeric_cols] = scaler.fit_transform(
    df[numeric_cols]
)

print("Scaling Completed")

df.to_csv(
    "processed_hr_dataset.csv",
    index=False
)

print("Dataset Saved")

spark = SparkSession.builder \
    .appName("AIDataEngineering") \
    .getOrCreate()

print("Spark Started")

spark_df = spark.read.csv(
    "processed_hr_dataset.csv",
    header=True,
    inferSchema=True
)

spark_df.show(5)

print("Rows:", spark_df.count())

print("Columns:")
spark_df.printSchema()

attrition_rate = (
    df["Attrition"].mean()
)

average_income = (
    df["MonthlyIncome"].mean()
)

average_age = (
    df["Age"].mean()
)

print(attrition_rate)
print(average_income)
print(average_age)

prompt = f"""
Generate business insights.

Metrics:

Attrition Rate:
{attrition_rate}

Average Income:
{average_income}

Average Age:
{average_age}

Provide:

1. Key Findings
2. Risks
3. Recommendations
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role":"user",
            "content":prompt
        }
    ]
)

insights = response.choices[0].message.content

print(insights)

report = f"""
# Automated Data Engineering Report

## Dataset

HR Employee Attrition Dataset

## Data Cleaning

Completed

## Feature Engineering

Completed

## Encoding

Completed

## Scaling

Completed

## KPI Metrics

- Attrition Rate: {attrition_rate}
- Average Income: {average_income}
- Average Age: {average_age}

## AI Insights

{insights}
"""

with open(
    "Final_Report.md",
    "w"
) as f:

    f.write(report)

print("Markdown Report Generated")

pdf = SimpleDocTemplate(
    "Final_Report.pdf"
)

styles = getSampleStyleSheet()

elements = []

elements.append(
    Paragraph(
        "Automated Data Engineering Report",
        styles["Title"]
    )
)

elements.append(
    Spacer(1,12)
)

elements.append(
    Paragraph(
        insights,
        styles["BodyText"]
    )
)

pdf.build(elements)

print("PDF Report Generated")

def data_engineering_agent():

    print("Step 1 : Load Dataset")

    print("Step 2 : Clean Dataset")

    print("Step 3 : Feature Engineering")

    print("Step 4 : Encoding")

    print("Step 5 : Scaling")

    print("Step 6 : PySpark Processing")

    print("Step 7 : KPI Analytics")

    print("Step 8 : AI Insights")

    print("Step 9 : Report Generation")

    print("Pipeline Completed")

data_engineering_agent()