# -*- coding: utf-8 -*-
"""Phase1_Capstone_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gG-3PvZ3fbjaq5-prWECMAQw20JKAuZ5
"""

import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

df = pd.read_csv("employee.csv")
df.head()
df.shape
df.info()
df.describe()
df.columns
df.isnull().sum()
df.duplicated().sum()

df_clean = df.copy()

df_clean.drop_duplicates(inplace=True)
df_clean.shape
df_clean.columns = df_clean.columns.str.lower()
df_clean.columns
df_clean.to_csv("cleaned_employee_data.csv",index=False)

conn = sqlite3.connect("employee_attrition.db")

df_clean.to_sql(
    "employees",
    conn,
    if_exists="replace",
    index=False
)

query = """
SELECT COUNT(*)
FROM employees
"""

pd.read_sql(query,conn)

query = """
SELECT age,
department,
monthlyincome
FROM employees
WHERE age > 40
"""
pd.read_sql(query,conn)

query = """
SELECT age,
monthlyincome
FROM employees
ORDER BY monthlyincome DESC
LIMIT 10
"""
pd.read_sql(query,conn)

query = """
SELECT AVG(monthlyincome)
AS average_salary
FROM employees
"""
pd.read_sql(query,conn)

query = """
SELECT department,
COUNT(*) AS total_employees
FROM employees
GROUP BY department
"""
pd.read_sql(query,conn)

query = """
SELECT age,
jobrole,
monthlyincome
FROM employees
WHERE monthlyincome > 10000
AND yearsatcompany > 5
"""
pd.read_sql(query,conn)

query = """
SELECT *,
CASE
WHEN age < 30
THEN 'Young'

WHEN age BETWEEN 30 AND 45
THEN 'Middle Age'

ELSE 'Senior'
END AS age_group

FROM employees
"""
transformed_df = pd.read_sql(query,conn)

query = """
SELECT *,

CASE
WHEN monthlyincome >= 10000
THEN 'High Income'

ELSE 'Regular Income'

END AS income_category

FROM employees
"""
transformed_df = pd.read_sql(query,conn)

transformed_df.to_csv(
    "transformed_employee_data.csv",
    index=False
)

def extract():

    data = pd.read_csv(
        "employee.csv"
    )

    return data

def transform(data):

    data.drop_duplicates(inplace=True)

    data.columns = data.columns.str.lower()

    return data

def load(data):

    data.to_csv(
        "etl_output.csv",
        index=False
    )

    print("Loaded Successfully")

data = extract()
data = transform(data)
load(data)

from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("Capstone") \
    .getOrCreate()

bronze_df = spark.read.csv(
    "employee.csv",
    header=True,
    inferSchema=True
)
bronze_df.write.mode(
    "overwrite"
).parquet("bronze")

silver_df = bronze_df.dropDuplicates()
silver_df = silver_df.na.drop()
silver_df.write.mode(
    "overwrite"
).parquet("silver")

from pyspark.sql.functions import avg
gold_df = silver_df.groupBy(
    "Department"
).agg(
    avg("MonthlyIncome").alias(
        "AverageSalary"
    )
)
gold_df.write.mode(
    "overwrite"
).parquet("gold")

comparison = pd.DataFrame({

"Feature":[
"File Size",
"Storage Efficiency",
"Read Speed",
"Write Speed",
"Compression"
],

"CSV":[
"Large",
"Low",
"Slow",
"Moderate",
"No"
],

"Parquet":[
"Small",
"High",
"Fast",
"Fast",
"Yes"
]

})

comparison

gold_parquet = spark.read.parquet(
    "gold"
)
gold_pandas = gold_parquet.toPandas()

gold_pandas.head()

df_clean['department'].value_counts().plot(
    kind='bar'
)
plt.title("Department Distribution")
plt.show()

plt.hist(
    df_clean['monthlyincome'],
    bins=20
)
plt.title("Monthly Income Distribution")
plt.show()

df_clean['attrition'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.title("Attrition Distribution")
plt.show()

ml_df = df_clean.copy()

le = LabelEncoder()

for col in ml_df.select_dtypes(
    include='object'
).columns:

    ml_df[col] = le.fit_transform(
        ml_df[col]
    )

X = ml_df.drop(
    'attrition',
    axis=1
)

y = ml_df['attrition']

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestClassifier(
    random_state=42
)

model.fit(
    X_train,
    y_train
)

pred = model.predict(
    X_test
)

accuracy = accuracy_score(
    y_test,
    pred
)

print("Accuracy:",accuracy)

print(classification_report(
    y_test,
    pred
))

cm = confusion_matrix(
    y_test,
    pred
)

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title("Confusion Matrix")

plt.show()